### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by wjdpwdn** [wjdpwdn/todoapp#1]
# 직접 GitHub Repository를 만들고, 아래 항목을 제작합니다.
- [x] 과제 제출 여부를 확인할 수 있게, public으로 제작합니다.

## 아래 파일을 포함합니다.
- [x] README.md
- [x] .gitignore
- [x] LICENSE

## GitHub Project Kanban
- [x] Todo App을 직접 만든다고 생각하고 이슈, 마일스톤을 스스로 정해봅니다.
- [x] GitHub Project Kanban을 만들고, 이슈와 마일스톤을 연결하고 칸반 뷰로 변경합니다
## Coz’ Git flow
- [ ] 직접 제작한 GitHub Repository에 main, dev 브랜치를 만듭니다.
- [ ] dev 브랜치에서 main 브랜치로 Pull Request를 최소 1회 시도합니다.
## Create React App을 활용해 프론트엔드 개발에 유용한 프레임워크를 설치해봅니다.
- [x] Redux
- [x] Styled-Component
- [x] ESLint, Prettier
